# Generated by Django 3.0.4 on 2020-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Action'), ('C', 'Comedy'), ('D', 'Drama'), ('R', 'Romance')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movieApp/moviePic'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('RA', 'Recently added'), ('MW', 'Most Watched'), ('TR', 'Top reted')], max_length=2),
        ),
    ]
