# Generated by Django 3.0.4 on 2020-03-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200326_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='movie.Movie'),
        ),
    ]
